# Generated by Django 4.2.4 on 2023-08-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="live_link",
            new_name="github_link",
        ),
        migrations.RemoveField(
            model_name="project",
            name="code_link",
        ),
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.TextField(help_text="Compétences acquises", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="highlights",
            field=models.TextField(help_text="Points forts du projet"),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.CharField(
                help_text="HTML, CSS, JavaScript, Python etc...", max_length=500
            ),
        ),
    ]
