# Generated by Django 4.2.4 on 2023-08-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_live_link_project_github_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="highlights",
        ),
        migrations.RemoveField(
            model_name="project",
            name="skills",
        ),
        migrations.AddField(
            model_name="project",
            name="soft_skills",
            field=models.TextField(help_text="Soft skills acquis", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="technical_skills",
            field=models.TextField(
                help_text="Compétences techniques acquises", null=True
            ),
        ),
    ]
