# Generated by Django 4.2.4 on 2023-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/",
                verbose_name="Image de profil",
            ),
        ),
    ]
